### ISSUE TITLE
Horrible freezing with Github Comment Enhancer

### ISSUE THREAD

**Issue by mzso** [jerone/UserScripts#104] opened 2016-04-16 18:34 UTC
Since a week or two now, whenever I open a github issue page the tab or the browser freezes, depending whether I have e10s enabled or not. It affects all channels, including stable.
You have to be logged in to github for this issue to present itself.

When I have e10s on  I get multiple "this page is slowing down firefox" alerts an may last more than a minute. With e10s off the whole browser freezes, but for a much shorter time.

I isolated this issue to this script. After disabling it the pages load normally.

**Comment by jerone** [comment] 2016-04-16 20:52
Duplicate of https://github.com/jerone/UserScripts/issues/97

**Closed by jerone** 2016-04-16 20:52 UTC

**Comment by mzso** [comment] 2016-04-17 10:41
It only happens for less than two weeks here. So I'm not sure how related are the two issues are.

I've been using this script for a lot longer than that.
