### ISSUE TITLE
Github Comment Enhancer doesn't work when making new issues

### ISSUE THREAD

**Issue by thenoncoder** [jerone/UserScripts#66] opened 2015-07-28 17:43 UTC
It only works in comments.
I understand that the name is *comment* enhancer, but couldn't you still make it work for all text input fields on Github?

**Comment by jerone** [comment] 2015-07-28 18:16
It should work on comments, issues, pull requests, inline comments, the wiki and comments on Gist.

Can you provide in clear steps where it doesn't work for you.

**Comment by thenoncoder** [comment] 2015-07-28 18:22
It works now for some reason.

**Comment by jerone** [comment] 2015-07-28 18:29
I noticed that in specific cases (particular sequence of steps) the script won't attach, but I haven't found a way to produce it yet :disappointed:

The problem is that GitHub uses pjax for page navigation, making it very hard to attach this script. If it doesn't work, a refresh should always work.

**Comment by thenoncoder** [comment] 2015-07-28 18:39
It works for me now, not sure why it doesn't work for you.

**Comment by Tailszefox** [comment] 2015-08-02 21:51
I've just got the same issue when trying to make a new issue. Indeed, refreshing worked. Perhaps the script should force a reload in cases like this?

**Comment by jerone** [comment] 2015-08-03 04:35
Again, I really would like to fix this issue too, but the way GitHub page navigation works (pjax) makes it really hard to detect real navigation actions. 

Without clear and reproducible steps I can't fix this issue :(

**Comment by Tailszefox** [comment] 2015-08-03 18:44
I think I caught one of the causes of the issue. It happens when navigation starts on a page where the script isn't set to run. Note that I'm using Firefox, perhaps it works differently with other browsers.

For example, if I start navigation on https://github.com/jerone/UserScripts/issues , the script gets triggered and everything works well. However, if I start navigation on https://github.com/jerone/UserScripts , or on https://github.com/jerone/UserScripts/issues?q=is%3Aissue+is%3Aclosed , the script isn't run, and thus doesn't attach to the pjax event. Hence, going anywhere from there means the script never triggers on any comment box.

One way I've found to solve this is to include the script on every page on GitHub:
`// @include     https://github.com/*/*`

Obviously, though, that may be a tad overkill, so it can probably be tweaked. In any case, with that, the script triggers consistently and is attaching every time.

**Comment by jerone** [comment] 2015-08-03 20:04
> if I start navigation on https://github.com/jerone/UserScripts , or on https://github.com/jerone/UserScripts/issues?q=is%3Aissue+is%3Aclosed , the script isn't run

Awesome, just confirmed. Will soon release a fix for this.

**Closed** 2015-08-17 19:17 UTC
Labels: (Github Comment Enhancer), bug
