### ISSUE TITLE
Interface got messed up.

### ISSUE THREAD

**Issue by mzso** [jerone/UserScripts#44] opened 2015-03-20 13:31 UTC
I noticed it yesterday first. I'm certain it was working two days ago. What could be the cause?
I didn't do anything in particular. And it doesn't seem to be a conflict with other usescripts or styles.
I'm on firefox 37 beta. Also Apparently it works properly on my nigthly profile with nightly. Which is strange. Usually stuff break on nightly and not the other way around.

![github_comment_enhancer _missing_emoticon_button_ _issue_ 37_ _jerone_userscripts_-_2015-03-20_14 26 30](https://cloud.githubusercontent.com/assets/4479090/6752264/35c068d4-cf0d-11e4-9cd2-bd55af022a6c.png)

PS:
The edit buttons don't appear when I'm posting a new issue. I don't see why they shouldn't

**Comment by jerone** [comment] 2015-03-20 14:32
Duplicate of https://github.com/jerone/UserScripts/issues/43 which just got fixed. Waiting for the repo's to grab the latest version...

**Closed by jerone** 2015-03-20 14:32 UTC
