### ISSUE TITLE
(Github_Comment_Enhancer) https://github.com/*/*/edit

### ISSUE THREAD

**Issue by vejobuj** [jerone/UserScripts#60] opened 2015-04-18 00:20 UTC
Would be possible to activate it for editing file markdown?
such as https://github.com/jerone/UserScripts/blob/master/README.md
I tried to include it like this but it doesn't seem to work.
//@include https://github.com/*/*/edit/*.md

Just discovered this great userscript. thanks.

**Comment by jerone** [comment] 2015-04-18 09:57
Actually I tried that too. The issue is that editing a file doesn't happen in a normal `<textarea>`, but in an online editor [Ace](http://ace.c9.io). This requires knowledge of hooking into Ace, which I don't have right now.

Closing a duplicate https://github.com/jerone/UserScripts/issues/45

**Closed by jerone** 2015-04-18 09:57 UTC
Labels: (Github Comment Enhancer), duplicate
